version: '3'
services:
  backend:
    container_name: openweather_backend
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      OPENWEATHER_API_KEY: XXXXXXXXX
    volumes:
      - ./backend:/myapp/backend
  frontend:
    container_name: openweather_frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/myapp/frontend
    depends_on:
      - backend
